---
contracts_folder: contracts
dependencies:
  - name: OpenZeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 4.5.0
solidity:
  import_remapping:
    - "@openzeppelin=OpenZeppelin/4.5.0"
ethereum:
  development:
    default_provider: hardhat
deployments:
  ethereum:
    goerli:
      - contract_type: Box
        address: 0x44B3f6d694283E3e4811E048d2f56429718b41F1
plugins:
  - name: solidity
    version: 0.1.0b5
  - name: hardhat
