---
contracts_folder: contracts
dependencies:
  - name: OpenZeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 4.5.0
solidity:
  import_remapping:
    - "@openzeppelin=OpenZeppelin/4.5.0"
ethereum:
  development:
    default_provider: hardhat
deployments:
  ethereum:
    goerli:
      - contract_type: DirectAds
        address: 0x15B70a02D92074651d416AfecaCA70AF8a97eb25
plugins:
  - name: solidity
    version: 0.1.0b5
  - name: hardhat
